apiversion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-ocp
  spec:
    params:
      - name: image
        type: string
    steps:
      - name: deploy
        image: quay.io/openshift/origin-cli:latest
        script: |
          #!/bin/bash
          APP_NAME=backend
          IMAGE=$(params.image)

          if oc get deployment ${APP_NAME} >/dev/null 2>&1; then
            echo "Updating deployment image...."
            oc set image deployment/${APP_NAME} ${APP_NAME}=${IMAGE}
          else
            echo "Creating new app..."
            oc new-app --name=${APP_NAME} ${IMAGE}
          fi
            
